# Generated by Django 5.1.4 on 2024-12-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_spam_identifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailspammodel',
            name='NotSpamProbability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailspammodel',
            name='SpamProbability',
            field=models.IntegerField(default=0),
        ),
    ]
